#!/bin/bash
# Bitcoin Core Node Setup Script for Testnet4
# This script helps set up Bitcoin Core for package broadcasting

set -e

echo "🚀 Bitcoin Core Node Setup for Testnet4"
echo "======================================"
echo ""

# Check if bitcoind is installed
if ! command -v bitcoind &> /dev/null; then
    echo "❌ Bitcoin Core (bitcoind) not found!"
    echo ""
    echo "Please install Bitcoin Core first:"
    echo "  Option 1: Download from https://bitcoincore.org/en/download/"
    echo "  Option 2: sudo apt-get install bitcoind bitcoin-cli (if PPA available)"
    echo ""
    exit 1
fi

echo "✅ Bitcoin Core found: $(bitcoind --version | head -1)"
echo ""

# Create data directory
DATA_DIR="$HOME/.bitcoin/testnet4"
CONFIG_FILE="$DATA_DIR/bitcoin.conf"

echo "📁 Creating data directory: $DATA_DIR"
mkdir -p "$DATA_DIR"

# Generate secure random password
RPC_PASSWORD=$(openssl rand -hex 32)
RPC_USER="charmcards_rpc"

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Config file already exists: $CONFIG_FILE"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing config. Exiting."
        exit 0
    fi
fi

# Create config file
echo "📝 Creating configuration file..."
cat > "$CONFIG_FILE" << EOF
# Bitcoin Core Configuration for Testnet4
# Generated by setup-bitcoin-node.sh

# Network
testnet=1

# RPC Configuration (REQUIRED for package broadcasting)
server=1
rpcuser=$RPC_USER
rpcpassword=$RPC_PASSWORD
rpcport=18332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1

# Performance
dbcache=1000
maxconnections=40

# Logging
logtimestamps=1
EOF

echo "✅ Configuration file created: $CONFIG_FILE"
echo ""
echo "🔑 RPC Credentials:"
echo "   Username: $RPC_USER"
echo "   Password: $RPC_PASSWORD"
echo ""
echo "⚠️  IMPORTANT: Save these credentials! You'll need them for your .env file."
echo ""

# Check if node is already running
if pgrep -x "bitcoind" > /dev/null; then
    echo "⚠️  Bitcoin Core is already running!"
    echo "   You may need to restart it for the new config to take effect."
    echo ""
    read -p "Do you want to stop the current node? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "🛑 Stopping Bitcoin Core..."
        pkill bitcoind || true
        sleep 2
    fi
fi

# Ask if user wants to start the node
read -p "Do you want to start Bitcoin Core now? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo "🚀 Starting Bitcoin Core..."
    bitcoind -testnet -datadir="$DATA_DIR" -daemon
    sleep 3
    
    # Check if it started successfully
    if pgrep -x "bitcoind" > /dev/null; then
        echo "✅ Bitcoin Core started successfully!"
        echo ""
        echo "📊 Checking node status..."
        sleep 2
        bitcoin-cli -testnet -datadir="$DATA_DIR" getblockchaininfo | head -10 || echo "   (Node is still starting up, this is normal)"
    else
        echo "❌ Failed to start Bitcoin Core. Check logs: tail -f $DATA_DIR/debug.log"
        exit 1
    fi
fi

echo ""
echo "======================================"
echo "✅ Setup Complete!"
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Update your api/.env file with:"
echo "   BITCOIN_RPC_URL=http://$RPC_USER:$RPC_PASSWORD@localhost:18332"
echo ""
echo "2. Or use separate variables:"
echo "   BITCOIN_RPC_URL=http://localhost:18332"
echo "   BITCOIN_RPC_USER=$RPC_USER"
echo "   BITCOIN_RPC_PASSWORD=$RPC_PASSWORD"
echo ""
echo "3. Restart your API server"
echo ""
echo "4. Check node status:"
echo "   bitcoin-cli -testnet -datadir=$DATA_DIR getblockchaininfo"
echo ""
echo "5. Monitor sync progress:"
echo "   tail -f $DATA_DIR/debug.log"
echo ""
echo "📚 For more details, see: BITCOIN_CORE_SETUP.md"
echo ""
