#!/bin/bash
# Bitcoin Core Node Setup Script for Testnet4
# This script helps set up Bitcoin Core for package broadcasting

set -e

echo "🚀 Bitcoin Core Node Setup for Testnet4"
echo "======================================"
echo ""

# Check if bitcoind is installed
if ! command -v bitcoind &> /dev/null; then
    echo "❌ Bitcoin Core (bitcoind) not found!"
    echo ""
    echo "Please install Bitcoin Core first:"
    echo "  Option 1: Download from https://bitcoincore.org/en/download/"
    echo "  Option 2: sudo apt-get install bitcoind bitcoin-cli (if PPA available)"
    echo ""
    exit 1
fi

echo "✅ Bitcoin Core found: $(bitcoind --version | head -1)"
echo ""

# Create data directory
DATA_DIR="$HOME/.bitcoin/testnet4"
CONFIG_FILE="$DATA_DIR/bitcoin.conf"

echo "📁 Creating data directory: $DATA_DIR"
mkdir -p "$DATA_DIR"

# Generate secure random password
RPC_PASSWORD=$(openssl rand -hex 32)
RPC_USER="charmcards_rpc"

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Config file already exists: $CONFIG_FILE"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing config. Exiting."
        exit 0
    fi
fi

# Create config file
echo "📝 Creating configuration file with performance optimizations..."
cat > "$CONFIG_FILE" << EOF
# Bitcoin Core Configuration for Testnet4
# Generated by setup-bitcoin-node.sh
# Optimized for fast sync and runtime performance

# Network - Use testnet4 chain
chain=testnet4

# RPC Configuration (REQUIRED for package broadcasting)
server=1
rpcuser=$RPC_USER
rpcpassword=$RPC_PASSWORD
rpcport=18332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1

# Memory Optimizations
# dbcache: Amount of RAM to use for block/undo/chainstate cache (MB)
# Higher values = faster block processing, less disk I/O
dbcache=9000

# maxmempool: Maximum mempool size (MB)
# Lower value prioritizes block sync over mempool operations
maxmempool=300

# maxorphantx: Maximum number of orphan transactions to keep in memory
# Lower value reduces memory usage during sync
maxorphantx=10

# CPU Optimizations
# par: Number of script verification threads
# Utilizes multiple CPU cores for faster verification
par=6

# Network Optimizations
# maxconnections: Maximum number of peer connections
# More peers = faster block download (testnet4 can handle more)
maxconnections=128

# blocksonly: Only download and relay blocks, not transactions
# Significantly faster initial sync, can disable after sync completes
blocksonly=1

# peerbloomfilters: Disable bloom filters (not needed for testnet4 operations)
# Reduces network overhead
peerbloomfilters=0

# listenonion: Disable Tor listener (if not using Tor)
# Reduces resource usage
listenonion=0

# Verification Optimizations (Testnet-specific)
# assumevalid: Block hash to assume valid (skips verification before this block)
# Uncomment and set to a known-good testnet4 block hash for faster sync
# To get the value: ./get-assumevalid.sh
# Or manually: bitcoin-cli -chain=testnet4 -datadir=$DATA_DIR getblockchaininfo | grep assumevalid
# assumevalid=0

# Disk I/O Optimizations
# txindex: Build full transaction index (disabled - not needed for basic operations)
txindex=0

# coinstatsindex: Build coin statistics index (disabled - not needed for basic operations)
coinstatsindex=0

# Logging
logtimestamps=1
EOF

echo "✅ Configuration file created: $CONFIG_FILE"
echo ""
echo "🔑 RPC Credentials:"
echo "   Username: $RPC_USER"
echo "   Password: $RPC_PASSWORD"
echo ""
echo "⚠️  IMPORTANT: Save these credentials! You'll need them for your .env file."
echo ""

# Check if node is already running
if pgrep -x "bitcoind" > /dev/null; then
    echo "⚠️  Bitcoin Core is already running!"
    echo "   You may need to restart it for the new config to take effect."
    echo ""
    read -p "Do you want to stop the current node? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "🛑 Stopping Bitcoin Core..."
        pkill bitcoind || true
        sleep 2
    fi
fi

# Ask if user wants to start the node
read -p "Do you want to start Bitcoin Core now? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo "🚀 Starting Bitcoin Core..."
    bitcoind -testnet -datadir="$DATA_DIR" -daemon
    sleep 3
    
    # Check if it started successfully
    if pgrep -x "bitcoind" > /dev/null; then
        echo "✅ Bitcoin Core started successfully!"
        echo ""
        echo "📊 Checking node status..."
        sleep 2
        bitcoin-cli -chain=testnet4 -datadir="$DATA_DIR" getblockchaininfo | head -10 || echo "   (Node is still starting up, this is normal)"
    else
        echo "❌ Failed to start Bitcoin Core. Check logs: tail -f $DATA_DIR/debug.log"
        exit 1
    fi
fi

echo ""
echo "======================================"
echo "✅ Setup Complete!"
echo ""
echo "⚡ Performance Optimizations Applied:"
echo "   - dbcache: 9000 MB (9GB) for faster block processing"
echo "   - maxconnections: 128 peers for faster download"
echo "   - blocksonly: Enabled for faster initial sync"
echo "   - par: 6 threads for parallel verification"
echo ""
echo "💡 Note: blocksonly mode is enabled for faster sync."
echo "   After sync completes, you can disable it by setting blocksonly=0"
echo "   in $CONFIG_FILE and restarting the node."
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Update your api/.env file with:"
echo "   BITCOIN_RPC_URL=http://$RPC_USER:$RPC_PASSWORD@localhost:18332"
echo ""
echo "2. Or use separate variables:"
echo "   BITCOIN_RPC_URL=http://localhost:18332"
echo "   BITCOIN_RPC_USER=$RPC_USER"
echo "   BITCOIN_RPC_PASSWORD=$RPC_PASSWORD"
echo ""
echo "3. Restart your API server"
echo ""
echo "4. Check node status:"
echo "   bitcoin-cli -chain=testnet4 -datadir=$DATA_DIR getblockchaininfo"
echo ""
echo "5. Monitor sync progress:"
echo "   ./monitor-bitcoin-sync.sh"
echo "   or: tail -f $DATA_DIR/debug.log"
echo ""
echo "6. To optimize an existing node, run:"
echo "   ./optimize-bitcoin-node.sh"
echo ""
echo "📚 For more details, see: SYNC_OPTIMIZATION_SUMMARY.md"
echo ""
